version: 2
updates:
  # Keep updates separate so auto-merge can enforce a single patch update type.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: ci
    labels: [dependencies]
    open-pull-requests-limit: 1

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: /
    schedule:
      interval: weekly
      day: sunday
    commit-message:
      prefix: "build(deps)"
    labels: [dependencies]
    open-pull-requests-limit: 3
