/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 109
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_include = 2,
  anon_sym_POUNDdefine = 3,
  anon_sym_POUNDifdef = 4,
  anon_sym_POUNDifndef = 5,
  anon_sym_POUNDelse = 6,
  anon_sym_POUNDendif = 7,
  sym_macro_name = 8,
  sym_line_comment = 9,
  sym_block_comment = 10,
  sym_integer_literal = 11,
  sym_string_literal = 12,
  anon_sym_true = 13,
  anon_sym_false = 14,
  sym_unset_value = 15,
  anon_sym_bit = 16,
  anon_sym_int = 17,
  anon_sym_string = 18,
  anon_sym_dag = 19,
  anon_sym_code = 20,
  anon_sym_bits = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_list = 24,
  anon_sym_class = 25,
  anon_sym_def = 26,
  anon_sym_COLON = 27,
  anon_sym_COMMA = 28,
  anon_sym_SEMI = 29,
  anon_sym_LBRACE = 30,
  anon_sym_RBRACE = 31,
  anon_sym_field = 32,
  anon_sym_EQ = 33,
  anon_sym_let = 34,
  anon_sym_append = 35,
  anon_sym_prepend = 36,
  anon_sym_defvar = 37,
  anon_sym_assert = 38,
  anon_sym_LBRACK = 39,
  anon_sym_RBRACK = 40,
  sym_source_file = 41,
  sym__top_level_item = 42,
  sym_include_directive = 43,
  sym_preprocessor_directive = 44,
  sym_boolean_literal = 45,
  sym__type = 46,
  sym_type = 47,
  sym_class_definition = 48,
  sym_def_definition = 49,
  sym_parent_class_list = 50,
  sym_parent_class = 51,
  sym_body = 52,
  sym__body_item = 53,
  sym_field_declaration = 54,
  sym_let_assignment = 55,
  sym_let_mode = 56,
  sym_defvar_statement = 57,
  sym_assert_statement = 58,
  sym__value = 59,
  sym_template_parameters = 60,
  sym_template_parameter = 61,
  sym_argument_list = 62,
  sym_range_list = 63,
  aux_sym_source_file_repeat1 = 64,
  aux_sym_parent_class_list_repeat1 = 65,
  aux_sym_body_repeat1 = 66,
  aux_sym_template_parameters_repeat1 = 67,
  aux_sym_argument_list_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_include] = "include",
  [anon_sym_POUNDdefine] = "#define",
  [anon_sym_POUNDifdef] = "#ifdef",
  [anon_sym_POUNDifndef] = "#ifndef",
  [anon_sym_POUNDelse] = "#else",
  [anon_sym_POUNDendif] = "#endif",
  [sym_macro_name] = "macro_name",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_integer_literal] = "integer_literal",
  [sym_string_literal] = "string_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_unset_value] = "unset_value",
  [anon_sym_bit] = "bit",
  [anon_sym_int] = "int",
  [anon_sym_string] = "string",
  [anon_sym_dag] = "dag",
  [anon_sym_code] = "code",
  [anon_sym_bits] = "bits",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_list] = "list",
  [anon_sym_class] = "class",
  [anon_sym_def] = "def",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_field] = "field",
  [anon_sym_EQ] = "=",
  [anon_sym_let] = "let",
  [anon_sym_append] = "append",
  [anon_sym_prepend] = "prepend",
  [anon_sym_defvar] = "defvar",
  [anon_sym_assert] = "assert",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_source_file] = "source_file",
  [sym__top_level_item] = "_top_level_item",
  [sym_include_directive] = "include_directive",
  [sym_preprocessor_directive] = "preprocessor_directive",
  [sym_boolean_literal] = "boolean_literal",
  [sym__type] = "_type",
  [sym_type] = "type",
  [sym_class_definition] = "class_definition",
  [sym_def_definition] = "def_definition",
  [sym_parent_class_list] = "parent_class_list",
  [sym_parent_class] = "parent_class",
  [sym_body] = "body",
  [sym__body_item] = "_body_item",
  [sym_field_declaration] = "field_declaration",
  [sym_let_assignment] = "let_assignment",
  [sym_let_mode] = "let_mode",
  [sym_defvar_statement] = "defvar_statement",
  [sym_assert_statement] = "assert_statement",
  [sym__value] = "_value",
  [sym_template_parameters] = "template_parameters",
  [sym_template_parameter] = "template_parameter",
  [sym_argument_list] = "argument_list",
  [sym_range_list] = "range_list",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parent_class_list_repeat1] = "parent_class_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_template_parameters_repeat1] = "template_parameters_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_include] = anon_sym_include,
  [anon_sym_POUNDdefine] = anon_sym_POUNDdefine,
  [anon_sym_POUNDifdef] = anon_sym_POUNDifdef,
  [anon_sym_POUNDifndef] = anon_sym_POUNDifndef,
  [anon_sym_POUNDelse] = anon_sym_POUNDelse,
  [anon_sym_POUNDendif] = anon_sym_POUNDendif,
  [sym_macro_name] = sym_macro_name,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_integer_literal] = sym_integer_literal,
  [sym_string_literal] = sym_string_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_unset_value] = sym_unset_value,
  [anon_sym_bit] = anon_sym_bit,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_dag] = anon_sym_dag,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_bits] = anon_sym_bits,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_list] = anon_sym_list,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_field] = anon_sym_field,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_append] = anon_sym_append,
  [anon_sym_prepend] = anon_sym_prepend,
  [anon_sym_defvar] = anon_sym_defvar,
  [anon_sym_assert] = anon_sym_assert,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_source_file] = sym_source_file,
  [sym__top_level_item] = sym__top_level_item,
  [sym_include_directive] = sym_include_directive,
  [sym_preprocessor_directive] = sym_preprocessor_directive,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym__type] = sym__type,
  [sym_type] = sym_type,
  [sym_class_definition] = sym_class_definition,
  [sym_def_definition] = sym_def_definition,
  [sym_parent_class_list] = sym_parent_class_list,
  [sym_parent_class] = sym_parent_class,
  [sym_body] = sym_body,
  [sym__body_item] = sym__body_item,
  [sym_field_declaration] = sym_field_declaration,
  [sym_let_assignment] = sym_let_assignment,
  [sym_let_mode] = sym_let_mode,
  [sym_defvar_statement] = sym_defvar_statement,
  [sym_assert_statement] = sym_assert_statement,
  [sym__value] = sym__value,
  [sym_template_parameters] = sym_template_parameters,
  [sym_template_parameter] = sym_template_parameter,
  [sym_argument_list] = sym_argument_list,
  [sym_range_list] = sym_range_list,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parent_class_list_repeat1] = aux_sym_parent_class_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_template_parameters_repeat1] = aux_sym_template_parameters_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDdefine] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDifdef] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDifndef] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUNDendif] = {
    .visible = true,
    .named = false,
  },
  [sym_macro_name] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_unset_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_bit] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_dag] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bits] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_list] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_field] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_append] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_prepend] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_defvar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_assert] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_item] = {
    .visible = false,
    .named = true,
  },
  [sym_include_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_preprocessor_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_def_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parent_class_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parent_class] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym__body_item] = {
    .visible = false,
    .named = true,
  },
  [sym_field_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_let_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_let_mode] = {
    .visible = true,
    .named = true,
  },
  [sym_defvar_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assert_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_template_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_template_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_range_list] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parent_class_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_template_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      ADVANCE_MAP(
        '"', 1,
        '#', 10,
        ',', 56,
        '/', 2,
        '0', 46,
        ':', 55,
        ';', 57,
        '<', 53,
        '=', 60,
        '>', 54,
        '?', 52,
        '[', 61,
        ']', 62,
        '{', 58,
        '}', 59,
        '+', 9,
        '-', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(51);
      if (lookahead == '\\') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(3);
      if (lookahead == '/') ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == '0') ADVANCE(47);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(36);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 29:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == '"' ||
          lookahead == '\'' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 't') ADVANCE(1);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '>') ADVANCE(54);
      if (lookahead == '}') ADVANCE(59);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUNDdefine);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_POUNDifdef);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_POUNDifndef);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_POUNDelse);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_POUNDendif);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_macro_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      if (('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      if (('G' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'b') ADVANCE(43);
      if (lookahead == 'x') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'b') ADVANCE(29);
      if (lookahead == 'x') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_unset_value);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'f', 5,
        'i', 6,
        'l', 7,
        'p', 8,
        's', 9,
        't', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'p') ADVANCE(11);
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(14);
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(30);
      END_STATE();
    case 16:
      if (lookahead == 'g') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'f') ADVANCE(32);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(33);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 20:
      if (lookahead == 'c') ADVANCE(35);
      if (lookahead == 't') ADVANCE(36);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(38);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 25:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_bit);
      if (lookahead == 's') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_dag);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_def);
      if (lookahead == 'v') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 34:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 35:
      if (lookahead == 'l') ADVANCE(50);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(52);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 42:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 43:
      if (lookahead == 'r') ADVANCE(56);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_bits);
      END_STATE();
    case 45:
      if (lookahead == 's') ADVANCE(57);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 47:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(60);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(61);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_list);
      END_STATE();
    case 52:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 55:
      if (lookahead == 'd') ADVANCE(64);
      END_STATE();
    case 56:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(66);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_field);
      END_STATE();
    case 61:
      if (lookahead == 'd') ADVANCE(67);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 63:
      if (lookahead == 'g') ADVANCE(69);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_append);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_assert);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_defvar);
      END_STATE();
    case 67:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 68:
      if (lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_prepend);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 33},
  [2] = {.lex_state = 33},
  [3] = {.lex_state = 33},
  [4] = {.lex_state = 33},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 33},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 33},
  [10] = {.lex_state = 33},
  [11] = {.lex_state = 33},
  [12] = {.lex_state = 33},
  [13] = {.lex_state = 33},
  [14] = {.lex_state = 33},
  [15] = {.lex_state = 33},
  [16] = {.lex_state = 33},
  [17] = {.lex_state = 33},
  [18] = {.lex_state = 33},
  [19] = {.lex_state = 33},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 33},
  [25] = {.lex_state = 33},
  [26] = {.lex_state = 33},
  [27] = {.lex_state = 33},
  [28] = {.lex_state = 33},
  [29] = {.lex_state = 33},
  [30] = {.lex_state = 33},
  [31] = {.lex_state = 33},
  [32] = {.lex_state = 33},
  [33] = {.lex_state = 33},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 33},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 33},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 33},
  [78] = {.lex_state = 33},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 33},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 33},
  [86] = {.lex_state = 33},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 33},
  [99] = {.lex_state = 33},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 33},
  [103] = {.lex_state = 33},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 6},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 33},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_POUNDdefine] = ACTIONS(1),
    [anon_sym_POUNDifdef] = ACTIONS(1),
    [anon_sym_POUNDifndef] = ACTIONS(1),
    [anon_sym_POUNDelse] = ACTIONS(1),
    [anon_sym_POUNDendif] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_integer_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_unset_value] = ACTIONS(1),
    [anon_sym_bit] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_dag] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_bits] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_list] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_field] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_append] = ACTIONS(1),
    [anon_sym_prepend] = ACTIONS(1),
    [anon_sym_defvar] = ACTIONS(1),
    [anon_sym_assert] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(106),
    [sym__top_level_item] = STATE(6),
    [sym_include_directive] = STATE(6),
    [sym_preprocessor_directive] = STATE(6),
    [sym_class_definition] = STATE(6),
    [sym_def_definition] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_include] = ACTIONS(7),
    [anon_sym_POUNDdefine] = ACTIONS(9),
    [anon_sym_POUNDifdef] = ACTIONS(9),
    [anon_sym_POUNDifndef] = ACTIONS(9),
    [anon_sym_POUNDelse] = ACTIONS(11),
    [anon_sym_POUNDendif] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [anon_sym_class] = ACTIONS(13),
    [anon_sym_def] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    ACTIONS(27), 1,
      anon_sym_field,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_defvar,
    ACTIONS(33), 1,
      anon_sym_assert,
    STATE(85), 1,
      sym__type,
    STATE(86), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(19), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
    STATE(3), 6,
      sym__body_item,
      sym_field_declaration,
      sym_let_assignment,
      sym_defvar_statement,
      sym_assert_statement,
      aux_sym_body_repeat1,
  [50] = 13,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    ACTIONS(27), 1,
      anon_sym_field,
    ACTIONS(29), 1,
      anon_sym_let,
    ACTIONS(31), 1,
      anon_sym_defvar,
    ACTIONS(33), 1,
      anon_sym_assert,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(85), 1,
      sym__type,
    STATE(86), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(19), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
    STATE(4), 6,
      sym__body_item,
      sym_field_declaration,
      sym_let_assignment,
      sym_defvar_statement,
      sym_assert_statement,
      aux_sym_body_repeat1,
  [100] = 13,
    ACTIONS(43), 1,
      anon_sym_bits,
    ACTIONS(46), 1,
      anon_sym_list,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    ACTIONS(51), 1,
      anon_sym_field,
    ACTIONS(54), 1,
      anon_sym_let,
    ACTIONS(57), 1,
      anon_sym_defvar,
    ACTIONS(60), 1,
      anon_sym_assert,
    STATE(85), 1,
      sym__type,
    STATE(86), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(37), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(40), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
    STATE(4), 6,
      sym__body_item,
      sym_field_declaration,
      sym_let_assignment,
      sym_defvar_statement,
      sym_assert_statement,
      aux_sym_body_repeat1,
  [150] = 8,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      anon_sym_include,
    ACTIONS(74), 1,
      anon_sym_class,
    ACTIONS(77), 1,
      anon_sym_def,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(71), 2,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
    ACTIONS(68), 3,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
    STATE(5), 6,
      sym__top_level_item,
      sym_include_directive,
      sym_preprocessor_directive,
      sym_class_definition,
      sym_def_definition,
      aux_sym_source_file_repeat1,
  [184] = 8,
    ACTIONS(7), 1,
      anon_sym_include,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      anon_sym_def,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(11), 2,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
    ACTIONS(9), 3,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
    STATE(5), 6,
      sym__top_level_item,
      sym_include_directive,
      sym_preprocessor_directive,
      sym_class_definition,
      sym_def_definition,
      aux_sym_source_file_repeat1,
  [218] = 10,
    ACTIONS(82), 1,
      sym_identifier,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      sym_body,
    STATE(69), 1,
      sym_parent_class_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(47), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(84), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [254] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(94), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(96), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [276] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(98), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(100), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [298] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(102), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(104), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [320] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(106), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(108), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [342] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(110), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(112), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [364] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(114), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(116), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [386] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(118), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(120), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [408] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(122), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(124), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [430] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(126), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(128), 11,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
      anon_sym_bits,
      anon_sym_list,
      anon_sym_RBRACE,
      anon_sym_field,
      anon_sym_let,
      anon_sym_defvar,
      anon_sym_assert,
  [452] = 8,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    STATE(70), 1,
      sym_template_parameter,
    STATE(85), 1,
      sym__type,
    STATE(102), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(19), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
  [482] = 8,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    STATE(71), 1,
      sym_template_parameter,
    STATE(85), 1,
      sym__type,
    STATE(102), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(19), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
  [512] = 7,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    STATE(85), 1,
      sym__type,
    STATE(103), 1,
      sym_type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(17), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(19), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
  [539] = 7,
    ACTIONS(130), 1,
      sym_identifier,
    ACTIONS(134), 1,
      anon_sym_GT,
    STATE(81), 1,
      sym_argument_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(67), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(132), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [566] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(136), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [582] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(138), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [598] = 6,
    ACTIONS(21), 1,
      anon_sym_bits,
    ACTIONS(23), 1,
      anon_sym_list,
    STATE(84), 1,
      sym__type,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(140), 2,
      sym_identifier,
      anon_sym_bit,
    ACTIONS(142), 4,
      anon_sym_int,
      anon_sym_string,
      anon_sym_dag,
      anon_sym_code,
  [622] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(144), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [638] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(146), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [654] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [670] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(150), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [686] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(152), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [702] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(154), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [718] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(156), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [734] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(158), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [750] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(160), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [766] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(162), 9,
      ts_builtin_sym_end,
      anon_sym_include,
      anon_sym_POUNDdefine,
      anon_sym_POUNDifdef,
      anon_sym_POUNDifndef,
      anon_sym_POUNDelse,
      anon_sym_POUNDendif,
      anon_sym_class,
      anon_sym_def,
  [782] = 5,
    ACTIONS(164), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(83), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(166), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [803] = 5,
    ACTIONS(168), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(97), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(170), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [824] = 5,
    ACTIONS(172), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(91), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(174), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [845] = 5,
    ACTIONS(176), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(92), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(178), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [866] = 5,
    ACTIONS(180), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(93), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(182), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [887] = 5,
    ACTIONS(184), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(74), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(186), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [908] = 5,
    ACTIONS(188), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(87), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(190), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [929] = 5,
    ACTIONS(192), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(194), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [950] = 5,
    ACTIONS(196), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(73), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(198), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [971] = 5,
    ACTIONS(200), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(86), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(107), 2,
      sym_boolean_literal,
      sym__value,
    ACTIONS(202), 3,
      sym_integer_literal,
      sym_string_literal,
      sym_unset_value,
  [992] = 8,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    ACTIONS(204), 1,
      anon_sym_LT,
    STATE(32), 1,
      sym_body,
    STATE(46), 1,
      sym_template_parameters,
    STATE(64), 1,
      sym_parent_class_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1018] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(206), 5,
      anon_sym_GT,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1030] = 6,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_body,
    STATE(59), 1,
      sym_parent_class_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1050] = 6,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_body,
    STATE(55), 1,
      sym_parent_class_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1070] = 4,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parent_class_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(210), 2,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1085] = 4,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(48), 1,
      aux_sym_parent_class_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 2,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1100] = 4,
    ACTIONS(214), 1,
      sym_identifier,
    STATE(80), 1,
      sym_let_mode,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(216), 2,
      anon_sym_append,
      anon_sym_prepend,
  [1115] = 3,
    ACTIONS(218), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(220), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1128] = 4,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(52), 1,
      aux_sym_parent_class_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(225), 2,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1143] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(225), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1153] = 4,
    ACTIONS(227), 1,
      anon_sym_EQ,
    ACTIONS(229), 1,
      anon_sym_LBRACK,
    STATE(90), 1,
      sym_range_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1167] = 4,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(29), 1,
      sym_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1181] = 3,
    ACTIONS(233), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [1193] = 4,
    ACTIONS(235), 1,
      anon_sym_GT,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_template_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1207] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(240), 3,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1217] = 4,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(30), 1,
      sym_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1231] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(242), 3,
      anon_sym_COLON,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1241] = 4,
    ACTIONS(244), 1,
      anon_sym_GT,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    STATE(57), 1,
      aux_sym_template_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1255] = 4,
    ACTIONS(248), 1,
      anon_sym_GT,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1269] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(252), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1279] = 4,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(25), 1,
      sym_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1293] = 4,
    ACTIONS(229), 1,
      anon_sym_LBRACK,
    ACTIONS(254), 1,
      anon_sym_EQ,
    STATE(94), 1,
      sym_range_list,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1307] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(256), 3,
      anon_sym_COMMA,
      anon_sym_SEMI,
      anon_sym_LBRACE,
  [1317] = 4,
    ACTIONS(250), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_GT,
    STATE(62), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1331] = 4,
    ACTIONS(260), 1,
      anon_sym_GT,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    STATE(68), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1345] = 4,
    ACTIONS(90), 1,
      anon_sym_SEMI,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      sym_body,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1359] = 4,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_GT,
    STATE(61), 1,
      aux_sym_template_parameters_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1373] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(235), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [1382] = 3,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(49), 1,
      sym_parent_class,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1393] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(260), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [1402] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(269), 2,
      anon_sym_GT,
      anon_sym_COMMA,
  [1411] = 3,
    ACTIONS(271), 1,
      anon_sym_SEMI,
    ACTIONS(273), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1422] = 3,
    ACTIONS(275), 1,
      anon_sym_SEMI,
    ACTIONS(277), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1433] = 3,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(53), 1,
      sym_parent_class,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1444] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(279), 2,
      sym_identifier,
      anon_sym_GT,
  [1453] = 2,
    ACTIONS(281), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1461] = 2,
    ACTIONS(283), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1469] = 2,
    ACTIONS(285), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1477] = 2,
    ACTIONS(287), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1485] = 2,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1493] = 2,
    ACTIONS(291), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1501] = 2,
    ACTIONS(293), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1509] = 2,
    ACTIONS(295), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1517] = 2,
    ACTIONS(297), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1525] = 2,
    ACTIONS(299), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1533] = 2,
    ACTIONS(301), 1,
      sym_integer_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1541] = 2,
    ACTIONS(303), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1549] = 2,
    ACTIONS(305), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1557] = 2,
    ACTIONS(307), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1565] = 2,
    ACTIONS(309), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1573] = 2,
    ACTIONS(227), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1581] = 2,
    ACTIONS(311), 1,
      sym_string_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1589] = 2,
    ACTIONS(313), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1597] = 2,
    ACTIONS(315), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1605] = 2,
    ACTIONS(317), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1613] = 2,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1621] = 2,
    ACTIONS(321), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1629] = 2,
    ACTIONS(142), 1,
      sym_integer_literal,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1637] = 2,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1645] = 2,
    ACTIONS(325), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1653] = 2,
    ACTIONS(327), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1661] = 2,
    ACTIONS(329), 1,
      sym_macro_name,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1669] = 2,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1677] = 2,
    ACTIONS(333), 1,
      anon_sym_SEMI,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1685] = 2,
    ACTIONS(335), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 184,
  [SMALL_STATE(7)] = 218,
  [SMALL_STATE(8)] = 254,
  [SMALL_STATE(9)] = 276,
  [SMALL_STATE(10)] = 298,
  [SMALL_STATE(11)] = 320,
  [SMALL_STATE(12)] = 342,
  [SMALL_STATE(13)] = 364,
  [SMALL_STATE(14)] = 386,
  [SMALL_STATE(15)] = 408,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 452,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 512,
  [SMALL_STATE(20)] = 539,
  [SMALL_STATE(21)] = 566,
  [SMALL_STATE(22)] = 582,
  [SMALL_STATE(23)] = 598,
  [SMALL_STATE(24)] = 622,
  [SMALL_STATE(25)] = 638,
  [SMALL_STATE(26)] = 654,
  [SMALL_STATE(27)] = 670,
  [SMALL_STATE(28)] = 686,
  [SMALL_STATE(29)] = 702,
  [SMALL_STATE(30)] = 718,
  [SMALL_STATE(31)] = 734,
  [SMALL_STATE(32)] = 750,
  [SMALL_STATE(33)] = 766,
  [SMALL_STATE(34)] = 782,
  [SMALL_STATE(35)] = 803,
  [SMALL_STATE(36)] = 824,
  [SMALL_STATE(37)] = 845,
  [SMALL_STATE(38)] = 866,
  [SMALL_STATE(39)] = 887,
  [SMALL_STATE(40)] = 908,
  [SMALL_STATE(41)] = 929,
  [SMALL_STATE(42)] = 950,
  [SMALL_STATE(43)] = 971,
  [SMALL_STATE(44)] = 992,
  [SMALL_STATE(45)] = 1018,
  [SMALL_STATE(46)] = 1030,
  [SMALL_STATE(47)] = 1050,
  [SMALL_STATE(48)] = 1070,
  [SMALL_STATE(49)] = 1085,
  [SMALL_STATE(50)] = 1100,
  [SMALL_STATE(51)] = 1115,
  [SMALL_STATE(52)] = 1128,
  [SMALL_STATE(53)] = 1143,
  [SMALL_STATE(54)] = 1153,
  [SMALL_STATE(55)] = 1167,
  [SMALL_STATE(56)] = 1181,
  [SMALL_STATE(57)] = 1193,
  [SMALL_STATE(58)] = 1207,
  [SMALL_STATE(59)] = 1217,
  [SMALL_STATE(60)] = 1231,
  [SMALL_STATE(61)] = 1241,
  [SMALL_STATE(62)] = 1255,
  [SMALL_STATE(63)] = 1269,
  [SMALL_STATE(64)] = 1279,
  [SMALL_STATE(65)] = 1293,
  [SMALL_STATE(66)] = 1307,
  [SMALL_STATE(67)] = 1317,
  [SMALL_STATE(68)] = 1331,
  [SMALL_STATE(69)] = 1345,
  [SMALL_STATE(70)] = 1359,
  [SMALL_STATE(71)] = 1373,
  [SMALL_STATE(72)] = 1382,
  [SMALL_STATE(73)] = 1393,
  [SMALL_STATE(74)] = 1402,
  [SMALL_STATE(75)] = 1411,
  [SMALL_STATE(76)] = 1422,
  [SMALL_STATE(77)] = 1433,
  [SMALL_STATE(78)] = 1444,
  [SMALL_STATE(79)] = 1453,
  [SMALL_STATE(80)] = 1461,
  [SMALL_STATE(81)] = 1469,
  [SMALL_STATE(82)] = 1477,
  [SMALL_STATE(83)] = 1485,
  [SMALL_STATE(84)] = 1493,
  [SMALL_STATE(85)] = 1501,
  [SMALL_STATE(86)] = 1509,
  [SMALL_STATE(87)] = 1517,
  [SMALL_STATE(88)] = 1525,
  [SMALL_STATE(89)] = 1533,
  [SMALL_STATE(90)] = 1541,
  [SMALL_STATE(91)] = 1549,
  [SMALL_STATE(92)] = 1557,
  [SMALL_STATE(93)] = 1565,
  [SMALL_STATE(94)] = 1573,
  [SMALL_STATE(95)] = 1581,
  [SMALL_STATE(96)] = 1589,
  [SMALL_STATE(97)] = 1597,
  [SMALL_STATE(98)] = 1605,
  [SMALL_STATE(99)] = 1613,
  [SMALL_STATE(100)] = 1621,
  [SMALL_STATE(101)] = 1629,
  [SMALL_STATE(102)] = 1637,
  [SMALL_STATE(103)] = 1645,
  [SMALL_STATE(104)] = 1653,
  [SMALL_STATE(105)] = 1661,
  [SMALL_STATE(106)] = 1669,
  [SMALL_STATE(107)] = 1677,
  [SMALL_STATE(108)] = 1685,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(104),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 5, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 5, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 4, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_assignment, 5, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 5, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_defvar_statement, 5, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_defvar_statement, 5, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assert_statement, 5, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assert_statement, 5, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field_declaration, 6, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_declaration, 6, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_assignment, 6, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_assignment, 7, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_assignment, 7, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor_directive, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_definition, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_directive, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor_directive, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_definition, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_def_definition, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [180] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [196] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parent_class_list, 3, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parent_class_list, 2, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parent_class, 1, 0, 0),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parent_class_list_repeat1, 2, 0, 0), SHIFT_REPEAT(77),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parent_class_list_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_parameter, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_parameters_repeat1, 2, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_parameters_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_parameters, 3, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_parameters, 4, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parent_class, 4, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parent_class, 3, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_parameter, 4, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 4, 0, 0),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_range_list, 3, 0, 0),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [331] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_mode, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tablegen(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tablegen",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
